### ISSUE TITLE
Research removing this redirect application in favor of DNS record update

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-proxy-redirect#3]
**What we're after**
As a way to reduce our maintenance burden, we could research removing this redirect app by updating DNS records for these apps. DNS record could route old app urls through existing CDN services.

It looks like a DNS record change may not be able to redirect to the same path on another domain (?), but we could have a friendly message asking folks to update their bookmarks if that's the case.

**Example:** 
User types in https://fec-prod-cms.app.cloud.gov/help-candidates-and-committees/registering-candidate/other-agency-requirements/ and with a DNS record update that would resolve to https://www.fec.gov/help-candidates-and-committees/registering-candidate/other-agency-requirements/

**Comment by lbeaufort** [comment]
@patphongs pointed out that we don't "own" the app.cloud.gov domain, which would make putting in a DNS record complicated and probably not the best approach to removing the redirect application.

**Comment by jason-upchurch** [comment]
I attended cloud.gov office hours (i think they own the domain), and they do confirm that a simple redirect is not in the offering.

Closing issue.
